#!/usr/bin/env bash
set -e
cd /Users/milo/Projects/mission-control
export CONVEX_DEPLOYMENT='cloud:proper-rat-443'

run() {
  npx convex run prospectEmails:create "$1" 2>&1
}

echo "Seeding prospect emails..."

run '{"prospectName":"Cleveland Clinic CD","company":"Cleveland Clinic","role":"Creative Director","email":"","subject":"Commercial retouching — we work with Mayo, and Cleveland Clinic is on the shortlist","body":"Hi,\n\nMayo Clinic has been a Look & Seen account for a while now — the level of craft their team requires for patient-facing campaigns and brand photography is a bar we'\''re built for, and I imagine Cleveland Clinic'\''s standards are identical.\n\nWe specialize in medical and healthcare commercial retouching: clean, technically precise, no over-processing — the kind of work that holds up in print, OOH, and broadcast without looking like a stock photo.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Healthcare","notes":"Mayo Clinic credential is the perfect door opener here."}'
echo "✓ Cleveland Clinic"

run '{"prospectName":"Art Director","company":"Conde Nast","role":"Art Director, Vogue Commercial Creative","email":"","subject":"Expanding the Look & Seen relationship — Allure, GQ, AD","body":"Hi,\n\nWe'\''ve been doing retouching for Vogue'\''s commercial side for a bit now and the work has been going well — wanted to reach out directly about bringing that same relationship to Allure, GQ, and Architectural Digest when the right project comes up.\n\nOur turnaround, editorial sensibility, and skin work translate directly across titles — we understand the Conde Nast visual standard and we'\''re already in the system.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Editorial","notes":"Existing Vogue relationship — expanding to other CN titles."}'
echo "✓ Conde Nast"

run '{"prospectName":"Head of Art Production","company":"Leo Burnett Chicago","role":"Head of Art Production","email":"","subject":"Retouching partner for Burnett production volume — based in Minneapolis","body":"Hi,\n\nLeo Burnett'\''s production output for Coca-Cola, P&G, and McDonald'\''s is the kind of volume that demands a retouching partner who can operate at that pace without dropping quality — we built Look & Seen specifically for that kind of sustained commercial work.\n\nWe'\''re Minneapolis-based (close to Chicago, same timezone), have digital tech experience on national shoots, and do a lot of work in food, lifestyle, and consumer product categories that map directly to your client roster.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Publicis network, massive production volume."}'
echo "✓ Leo Burnett Chicago"

run '{"prospectName":"Head of Art Production","company":"Energy BBDO Chicago","role":"Head of Art Production","email":"","subject":"Look & Seen — retouching for BBDO Chicago campaigns","body":"Hi,\n\nEnergy BBDO'\''s been on the Ad Age A-List two years running for a reason — the production quality on your national brand work is consistently excellent, and that requires a retouching partner that doesn'\''t slow the machine down.\n\nWe'\''re Look & Seen, a Minneapolis studio with credits at Target, On Running, and several major national campaigns — same market, short flights, and we move fast on deadlines.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"BBDO worldwide, Ad Age A-List 2025."}'
echo "✓ Energy BBDO Chicago"

run '{"prospectName":"Director of Creative Photography","company":"General Mills","role":"Director of Creative Photography","email":"","subject":"Look & Seen — local retouching partner for General Mills","body":"Hi,\n\nGolden Valley and Minneapolis — we'\''re practically neighbors, and that matters when you'\''re running the kind of food and lifestyle photography volume General Mills produces in-house.\n\nWe'\''ve done commercial retouching and on-set digital tech for a lot of consumer product shoots and know what it takes to make food look real and appetizing without the artificial polish that screams retouched.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"DTC/CPG","notes":"Fortune 500, local to Minneapolis, massive photo volume."}'
echo "✓ General Mills"

run '{"prospectName":"Creative Director","company":"Medtronic","role":"Creative Director","email":"","subject":"Medical device photography retouching — we work with Mayo","body":"Hi,\n\nMedtronic'\''s marketing photography sits in a specific category — it has to be medically credible, emotionally resonant, and polished enough for a Fortune 100 brand. We know that space well from our work with Mayo Clinic, and I think the standards translate directly.\n\nLook & Seen is a Minneapolis retouching studio focused on commercial and healthcare photography — Fridley to Minneapolis is nothing, and we'\''ve never missed a medical campaign deadline.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Healthcare","notes":"World'\''s largest medtech, local to Minneapolis."}'
echo "✓ Medtronic"

run '{"prospectName":"Jonathan Cheung","company":"Lululemon","role":"Global Creative Director","email":"","subject":"Look & Seen — retouching and AI generation for Lululemon campaign work","body":"Hi Jonathan,\n\nThe direction you'\''ve been taking Lululemon'\''s creative since joining — that tension between athletic utility and fashion-forward editorial — is a look that requires really precise retouching to land correctly. Too much and it loses the authenticity. Too little and it doesn'\''t hit the quality bar.\n\nWe do high-end commercial retouching for athletic and fashion brands, and we'\''ve been building out AI image generation as a production tool — useful for rapid concepting when you want to pressure-test a campaign direction before committing to a full shoot.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Fashion","notes":"Named contact. New GCD hired 2024, former Gap/Levi."}'
echo "✓ Lululemon"

run '{"prospectName":"Head of Brand Creative","company":"On Running","role":"Head of Brand Creative (US)","email":"","subject":"Expanding our work together as On Running US presence grows","body":"Hi,\n\nWe'\''ve been proud to support On Running'\''s creative work as it'\''s scaled in the US — and with the brand'\''s growth trajectory and the new campaign directions you'\''re running, I wanted to open a conversation about deepening that relationship.\n\nWhether it'\''s increased retouching volume, digital tech support on set for upcoming US shoots, or using AI generation to concept campaign variations before you fly the crew — we'\''re built to grow with you.\n\nHappy to send examples of our expanded work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Brand","notes":"Existing client — relationship expansion play."}'
echo "✓ On Running"

run '{"prospectName":"Head of Production","company":"72andSunny","role":"Head of Production","email":"","subject":"Look & Seen — production retouching for 72 lifestyle campaigns","body":"Hi,\n\n72andSunny'\''s on the A-List back to back for a reason — the photo direction on your lifestyle campaigns is consistently some of the best in the industry, and that quality requires a retouching partner who doesn'\''t water it down in post.\n\nWe'\''re Look & Seen, a Minneapolis studio with credits at Target, Nike, and On Running — we do commercial retouching, on-set digital tech, and AI image generation for brands that care about craft.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Ad Age A-List 2024 and 2025, LA/Brooklyn offices."}'
echo "✓ 72andSunny"

run '{"prospectName":"Head of Production","company":"Wieden+Kennedy New York","role":"Head of Production","email":"","subject":"Look & Seen — retouching for W+K NY (we'\''re already in the Nike portfolio)","body":"Hi,\n\nWe'\''ve done retouching for Nike campaigns, so we already know the visual standard that W+K demands — and we know you can'\''t send that work to a generalist shop and expect it to come back right.\n\nLook & Seen is a Minneapolis-based commercial retouching studio — on-set digital tech experience, fast turnaround on campaign assets, and AI generation capability for concepts. Stanley Post handles your UK retouching; we'\''d love to be the conversation for the US side.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Priority target. Nike in L&S portfolio. NY office opening."}'
echo "✓ Wieden+Kennedy New York"

run '{"prospectName":"Creative Director","company":"Periscope","role":"Creative Director","email":"","subject":"Look & Seen — local retouching partner for Periscope","body":"Hi,\n\nPeriscope runs photo-heavy retail and lifestyle work for Target, Bridgestone, and Raw Sugar — and we work with Target directly, so we already understand the pace and visual standard those relationships require.\n\nWe'\''re Minneapolis-based, which means no timezone friction, and we have experience across the full retouching pipeline — campaign photography, product, lifestyle, and on-set digital tech support.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Largest indie agency in Twin Cities, Target is a shared client."}'
echo "✓ Periscope"

run '{"prospectName":"Signe Peterson","company":"Allina Health","role":"Director of Marketing & Brand Expression","email":"","subject":"Commercial retouching for Allina Health — local studio, Mayo credential","body":"Hi Signe,\n\nAllina Health'\''s marketing photography — Abbott Northwestern, United Hospital, the system brand — sits in the same category as Mayo Clinic'\''s work, which we'\''ve been retouching for a while now. The technical and emotional precision required is something most generalist shops can'\''t deliver.\n\nWe'\''re Look & Seen, a Minneapolis studio, and we'\''ve built our healthcare retouching practice around exactly this type of work: medically credible, warm, and polished enough for a top health system'\''s standard.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Healthcare","notes":"Named contact. Local Minneapolis, Mayo credential is key."}'
echo "✓ Allina Health"

run '{"prospectName":"Creative Director","company":"Colle McVoy","role":"Creative Director","email":"","subject":"Look & Seen — Minneapolis retouching for food and brand campaigns","body":"Hi,\n\nColle McVoy'\''s work for Land O'\''Lakes, McCormick, and Crystal Farms requires exactly the kind of retouching that'\''s easy to get wrong — food photography especially is all in the detail, the lighting hold, the texture that reads real.\n\nWe'\''re Look & Seen, a Minneapolis studio, and we love working with agencies that care about craft — your B Corp status tells me you think about quality the same way we do. We can turn around campaign retouching at agency pace without sacrificing what makes the image worth looking at.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Ad Age Best Agency 2024, BCorp, local Minneapolis."}'
echo "✓ Colle McVoy"

run '{"prospectName":"Head of Art Production","company":"Carmichael Lynch","role":"Head of Art Production","email":"","subject":"Look & Seen — your Minneapolis retouching partner for Subaru, Porsche, and Harley","body":"Hi,\n\nCarmichael Lynch'\''s automotive and lifestyle campaigns — Subaru'\''s emotional storytelling, the Porsche precision, Harley'\''s grit — all require retouching that serves the brand voice instead of homogenizing it. That'\''s a narrow craft and it'\''s what we do.\n\nWe'\''re right here in Minneapolis, we'\''ve worked on major national campaigns across automotive, lifestyle, and consumer products, and we can support on-set digital tech or take assets post-production — whatever the shoot requires.\n\nHappy to send examples of our work — would a quick call make sense?\n\nDave Sweeney\nLook & Seen, Inc.\nlookandseen.com","category":"Agency","notes":"Tier 1 local agency, Subaru/Porsche/Harley clients."}'
echo "✓ Carmichael Lynch"

echo ""
echo "All done!"
